version: '3.7'
services:
  jenkins:
    image: 'dirane/jenkins-docker-ansible-clair'
    container_name: jenkins
    privileged: true #Pour permettre à notre container jenkins de démarrer des containers
    ports:
      - '8080:8080'
      - '444:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
      - '/var/run/docker.sock:/var/run/docker.sock' #Pour utiliser le client docker de la machine hôte
    networks:
      - pozos
volumes:
  jenkins_data:
    driver: local

networks:
  default:
    external: #Pour utiliser un réseau existant
      name: pozos
